// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU44eqvrt_LO2Sk2wuB7Zhe0cGLoLWWJE',
    appId: '1:24249137468:web:fd017a6ca15c1fee0a4639',
    messagingSenderId: '24249137468',
    projectId: 'project-note-bca4a',
    authDomain: 'project-note-bca4a.firebaseapp.com',
    storageBucket: 'project-note-bca4a.appspot.com',
    measurementId: 'G-6ZXW4SN246',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwiEocAmzI4kQv8aLT5kAhFEAZusaPw_I',
    appId: '1:24249137468:android:8ab960f1c8987de50a4639',
    messagingSenderId: '24249137468',
    projectId: 'project-note-bca4a',
    storageBucket: 'project-note-bca4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71XZSlkAEyZwJHp-AhvbaRKicSG8W9YA',
    appId: '1:24249137468:ios:c750233aa855d2c80a4639',
    messagingSenderId: '24249137468',
    projectId: 'project-note-bca4a',
    storageBucket: 'project-note-bca4a.appspot.com',
    iosClientId: '24249137468-cc0h2pniapqvbd09o54afrd4hjuoi4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71XZSlkAEyZwJHp-AhvbaRKicSG8W9YA',
    appId: '1:24249137468:ios:c750233aa855d2c80a4639',
    messagingSenderId: '24249137468',
    projectId: 'project-note-bca4a',
    storageBucket: 'project-note-bca4a.appspot.com',
    iosClientId: '24249137468-cc0h2pniapqvbd09o54afrd4hjuoi4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectNote',
  );
}
